//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artwork_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artwork
    {
        public int ArtworkID { get; set; }
        public string AssetNumber { get; set; }
        public string ArtTitle { get; set; }
        public Nullable<int> ArtTypeID { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public Nullable<int> CurrentLocationID { get; set; }
        public byte[] Image { get; set; }
        public string PhysicalDimension { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Levels { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string FileExtension { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> Section { get; set; }
        public Nullable<System.DateTime> RecordCreationDate { get; set; }
        public Nullable<System.DateTime> RecordLastUpdateDate { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Country Country { get; set; }
        public virtual CurrentLocation CurrentLocation { get; set; }
        public virtual Level Level { get; set; }
        public virtual Vendor Vendor1 { get; set; }
        public virtual ArtType ArtType { get; set; }
        public virtual Section Section1 { get; set; }
    }
}
