//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artwork_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Artworks = new HashSet<Artwork>();
        }
    
        public int VendorID { get; set; }
        public string Vendor1 { get; set; }
    
        public virtual ICollection<Artwork> Artworks { get; set; }
    }
}
